// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package storage

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgtype"
)

type Post struct {
	ID           uuid.UUID      `db:"id" json:"id"`
	AuthorID     uuid.UUID      `db:"author_id" json:"authorID"`
	Title        string         `db:"title" json:"title"`
	Previewimage sql.NullString `db:"previewimage" json:"previewimage"`
	Content      pgtype.JSONB   `db:"content" json:"content"`
	CreatedAt    time.Time      `db:"created_at" json:"createdAt"`
}
