// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type RegisterRequest struct {
	Email string `json:"email"`
	Name  string `json:"name"`
}

type User struct {
	ID    string `json:"id"`
	Email string `json:"email"`
	Name  string `json:"name"`
}
