{{ define "header" }}
{{- $tags := tags -}}
{{- $inject := inject -}}
{{- if $tags -}}
//go:build{{ range $tags }} {{ . }}{{ end }}

{{ end -}}
{{- if first -}}
// Package {{ pkg }} contains generated code for schema '{{ schema }}'.
{{ end -}}
package {{ pkg }}

// Code generated by xo. DO NOT EDIT.

import (
	"context"
	"database/sql"
	"database/sql/driver"
	"encoding/csv"
	"errors"
	"fmt"
	"io"
	"io/ioutil"
	"regexp"
	"strings"
	"time"
	"gorm.io/gorm"
	"boilerplate/internal/db"
{{- if driver "postgres" }}
	"github.com/lib/pq/hstore"
	_ "github.com/lib/pq"
{{ end }}{{ range imports }}
	{{ with .Alias }}{{ . }} {{ end }}{{ .Pkg }}
{{ end }}
)

{{- if $inject }}
{{ $inject }}
{{- end }}
{{ end }}
