output:
  ./internal/post/action/actions_gen.go
package: action
generate:
  models: true
  modulus-actions: true
output-options:
  skip-prune: true
import-mapping:
  ../user/user.yaml: boilerplate/internal/user/action