openapi: 3.0.3
info:
  title: User module
  description: The REST API for the user module
  version: 1.0.0
servers:
  - url: "http://localhost:8181"
## components
components:
  ## response objects
  schemas:
    Post:
      type: object
      required:
        - id
        - title
      properties:
        id:
          type: string
        title:
          type: string
        author:
          $ref: "../user/user.yaml#/components/schemas/User"
    PostList:
      type: array
      items:
        $ref: "#/components/schemas/Post"


  ## request objects
  requestBodies:
    CreatePostBody:
      content:
        application/json:
          schema:
            type: object
            required:
              - title
            properties:
              title:
                type: string
          example:
            title: "The first post"

  ## path parameters
  parameters:
    postId:
      in: path
      description: Post ID
      name: id
      required: true
      schema:
        type: string

## paths
paths:
  "/posts/{id}":
    get:
      operationId: GetPost
      summary: Get a post
      parameters:
        - $ref: "#/components/parameters/postId"
      responses:
        "200":
          description: One post.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
  "/posts":
    get:
      operationId: GetPostList
      summary: Get a post
      parameters:
        - in: query
          name: count
          schema:
            type: integer
            default: 10
            maximum: 100
            minimum: 1
          required: true

      responses:
        "200":
          description: List of posts.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostList'
